language: python
python:
  - 3.7
services:
  - docker
install:
  - docker build -t max-rec .
  - docker run -it -d -p 5000:5000 max-rec
  - pip install -r requirements-test.txt
before_script:
  - flake8 . --max-line-length=127 --exclude training/training_code/dataset
  - bandit -r .
  - sleep 30
script:
  - pytest tests/test.py
